// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.0
// source: proto/ai_agent.proto

package ai_agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Input struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Input) Reset() {
	*x = Input{}
	mi := &file_proto_ai_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_proto_ai_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Input) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type Output struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_proto_ai_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_proto_ai_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Output) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proto_ai_agent_proto protoreflect.FileDescriptor

const file_proto_ai_agent_proto_rawDesc = "" +
	"\n" +
	"\x14proto/ai_agent.proto\x12\bai_agent\"\x1d\n" +
	"\x05Input\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"$\n" +
	"\x06Output\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2;\n" +
	"\x05Agent\x122\n" +
	"\rQueryDeepseek\x12\x0f.ai_agent.Input\x1a\x10.ai_agent.OutputB\x11Z\x0f/proto/ai_agentb\x06proto3"

var (
	file_proto_ai_agent_proto_rawDescOnce sync.Once
	file_proto_ai_agent_proto_rawDescData []byte
)

func file_proto_ai_agent_proto_rawDescGZIP() []byte {
	file_proto_ai_agent_proto_rawDescOnce.Do(func() {
		file_proto_ai_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_agent_proto_rawDesc), len(file_proto_ai_agent_proto_rawDesc)))
	})
	return file_proto_ai_agent_proto_rawDescData
}

var file_proto_ai_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_ai_agent_proto_goTypes = []any{
	(*Input)(nil),  // 0: ai_agent.Input
	(*Output)(nil), // 1: ai_agent.Output
}
var file_proto_ai_agent_proto_depIdxs = []int32{
	0, // 0: ai_agent.Agent.QueryDeepseek:input_type -> ai_agent.Input
	1, // 1: ai_agent.Agent.QueryDeepseek:output_type -> ai_agent.Output
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ai_agent_proto_init() }
func file_proto_ai_agent_proto_init() {
	if File_proto_ai_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_agent_proto_rawDesc), len(file_proto_ai_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_agent_proto_goTypes,
		DependencyIndexes: file_proto_ai_agent_proto_depIdxs,
		MessageInfos:      file_proto_ai_agent_proto_msgTypes,
	}.Build()
	File_proto_ai_agent_proto = out.File
	file_proto_ai_agent_proto_goTypes = nil
	file_proto_ai_agent_proto_depIdxs = nil
}
