# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ai_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61i_agent.proto\x12\x08\x61i_agent\"\x16\n\x05Input\x12\r\n\x05query\x18\x01 \x01(\t\"\x1a\n\x06Output\x12\x10\n\x08response\x18\x01 \x01(\t2;\n\x05\x41gent\x12\x32\n\rQueryDeepseek\x12\x0f.ai_agent.Input\x1a\x10.ai_agent.Outputb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUT']._serialized_start=28
  _globals['_INPUT']._serialized_end=50
  _globals['_OUTPUT']._serialized_start=52
  _globals['_OUTPUT']._serialized_end=78
  _globals['_AGENT']._serialized_start=80
  _globals['_AGENT']._serialized_end=139
# @@protoc_insertion_point(module_scope)
